# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c00c566c0f316a84bfe68d8ecdaee55b611cbac71d0aeafc81ce5f587a23c86f66fbb2273ff3aad55654101e76e37ee3e1107b71eacc14094e410d2744d0bd7

test:
  secret_key_base: fe753df69fe21e733ad756f8390d8d418366367bcda4a0983090f47556db7d11c8e6c64247cf4bd4950750ee58102c7421056e48ee4bb67a806e744fa5ba609b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
# RAILS_ENV=production rake secret
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # secret_key_base: b67ae247114b3ab75485624fbc23c8ff0582ab40a51a5d43efe3f2a9cbb802e9358e3c55f241464acd2a1ba3c33255724a1c006a6eb943ee28628c81d4fdf4c9